[package]
name = "wl"
version = "0.1.0"
authors = ["AidoP <aidop@me.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
once_cell = "1.9"
wl-macro = { path = "../wl-macro" }
#wl-macro = { git = "https://github.com/AidoP/wl-macro" }