name = "Example Protocol"

[[interface]]
name = "c_init"
summary = "Bootstrap object"
description = "A singleton that allows instanciating further objects"
version = 1

[[interface.enum]]
name = "error"
summary = "Basic error type"
description = "A type for reporting high-level errors"
[[interface.enum.entry]]
name = 'invalid_object'
summary = "Object does not exist"
value = 0

[[interface.request]]
name = 'read'
summary = "Get a fd"
description = "Read from the given file"
[[interface.request.arg]]
name = 'fd'
type = 'fd'
summary = 'file descriptor for reading'

[[interface.event]]
name = 'error'
summary = 'Fatal error event'
description = "An error was reported"
[[interface.event.arg]]
name = 'object_id'
type = 'object'
summary = 'object where the error occurred'
[[interface.event.arg]]
name = 'code'
type = 'uint'
summary = 'Error code'
[[interface.event.arg]]
name = 'message'
type = 'string'
summary = 'Error description'